name: Feature POC
on: 
 push: 
  branches: 
    - develop
jobs:
  feast-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feast pandas scikit-learn pyarrow pyspark cryptography snowflake-connector-python
      - name: Genarate Feature CSV
        run: |
          cd madule_5_compute_engine/feature_repo pythin demo_usecase.py
      - name: Validate feast
        run: feast version
      - name: Execute Compute Engine
        run: |
          cd module_5_compute_engine/feature_repo
          feast apply
      - name: Run high value customer usecase
        run: |
          cd module_5_compute_engine/feature_repo
          python demo_usecase.py
      - name: Generate Churn Data
        run: |
          python module_5_compute_engine/generate.py
          
      - name: Materialize feast features
        run: |
          cd module_5_compute_engine/feature_repo
          feast materialize-incremental 2026-06-23T07:39:46
      - name: Run churn prediction usecase
        run: |
          python module_5_compute_engine/predict_.churn.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: feast result
          path: .
          
        
          
        
        
          
          
          
        
    
    
